### ISSUE TITLE
一部の動画でアスペクト比がずれる

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#1]
~~どちらに報告すればわからなかったのでとりあえずこちらへ（Twitterのがよかったですかね？）~~
Twitterにリプくださいってありましたね、すいません…

一部の動画で動画のアスペクト比がずれるようです

ずれる例
http://www.nicovideo.jp/watch/1307696392
http://www.nicovideo.jp/watch/sm25423456
http://www.nicovideo.jp/watch/sm700256

動画タイプは一番下のみがFLVで他はMP4です

http://nicowiki.com/encode.html#mb8c5b74
こちらにアップされたときのサーバー側の処理がありますが、
もしかしたらここら辺が関係してるかもです

こちらの環境は
Win 8.1
Adobe Flash 19.0.0.185
です

**Comment by mrtska** [comment]
上記の動画3つに関しては
2c5cd75a2bf14c1a4135450fd169cb0f6c9ff6c7
でうまく表示されるようにしました。おそらく他の4:3の動画でも大丈夫だとは思います。

なにかありましたらまたTwitterでリプライ、またはIssueでも構いません。

ではでは。

**Comment by S--Minecraft** [comment]
修正されたことを確認できました

ありがとうございます
