### ISSUE TITLE
特定操作時に動作停止 +要望

### ISSUE THREAD

**Issue by Z1360** [mrtska/SRNicoNico#113]
任意のユーザーを開いてマイリストタブを選択し、
任意のマイリストに対して右クリックメニューウィンドウを呼び出します。
「webviewで開く」をダブルクリック、またはクリックした瞬間にNicoNicoViewerのウィンドウ位置どこでもいいのでクリックすると確実にクラッシュします。
その時エラーウィンドウが表示されずに(エラー時の音は出る)「NicoNicoViewerは動作を停止しました。」という標準のダイアログが表示されます。

以下動作環境
ニコニコ動画アカウント 一般会員
OS Windows10 HOME 64bit
OSビルド 1709
プロセッサ i7 6700K
グラフィックボード GTX1080

ここから要望
アップデート時なのですが、
現在はアップデート後は終了するまで特権モードで動いています。
可能であればアップデート後も一般権限モードで起動するように検討お願い致します。

**Comment by mrtska** [comment]
0db9b7fd76c7667b4d6feadd2ba1a9179bd89181 でクラッシュするのは修正しました。

おっしゃる通りアップデート時にアップデーターが特権モードで動いている状態でNicoNicoViewerを起動する関係でアップデート時のみ特権モードで動いてしまっています。

ちょっと対策を考えます。

**Comment by Z1360** [comment]
アップデーターのフロントエンドを用意して、それが改めてNicoNicoViewer Updater.exeを呼び出すとかどうでしょうか

NicoNicoViewer→アップデートフロントエンド.exe呼び出し(一般権限)
    ↳アップデーターフロントエンド.exe→NicoNicoViewer Updater.exe呼び出し(管理者権限実行 フロントエンドはNicoNicoViewer Updater.exeが終わるまで待機)
        ↳NicoNicoViewer Updater.exe
    ↳アップデーターフロントエンドがNicoNicoViewerを呼び出す
でどうでしょうか

できるかどうか全く検証していません(爆
恐らく問題は特権モードのプロセスが外部プログラムを呼び出すことだと思うので
何か間に挟めばいいのかと思います。
お時間がありましたらどうぞ・・・

**Comment by mrtska** [comment]
結局自動起動せずに手動で起動してもらうことにしました。
