### ISSUE TITLE
アンインストールの手段を用意してほしい

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#119]
アンインストーラーが用意されていないため、コントロールパネルからもアンインストールできません。
アンインストールする手段が欲しいです。

**Comment by mrtska** [comment]
NicoNicoViewerのインストーラは中身を指定の場所に解凍しているだけなので、インストールしたファイルを削除すればアンインストールしたと同義かと思います。

インストーラはインストールの敷居を低くするために作成しましたがアンインストーラまではちょっと用意するのは・・・というのが本音です。
