### ISSUE TITLE
リダイレクトが起こる動画が読み込めない

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#12]
一部のコミュニティ動画?などのリダイレクトが発生する動画が読み込めないです

発生動画例: http://www.nicovideo.jp/watch/so20932444 → http://www.nicovideo.jp/watch/1369238005

**Comment by mrtska** [comment]
報告ありがとうございます。試したところ、私の環境では普通に再生されました。
何か条件があるんですかね。

**Comment by S--Minecraft** [comment]
さっき再生したらいけました…
何度か起きたのでそうかと思ったのですが、
ただ単に環境の問題かもしれないですね…
