### ISSUE TITLE
WEBVIEWで生放送視聴時に頻発するエラーについて（一般会員）

### ISSUE THREAD

**Issue by Nima128** [mrtska/SRNicoNico#125]
---------------------------
エラー
---------------------------
不明なエラーが発生しました。可能であれば、この文章をコピーして作者に報告していただれば幸いです。Ctrl+Cでコピーできます。
動画再生時に起きた場合は動画IDを添えてください。
 ExceptionObject:System.NotSupportedException: この型の CollectionView は、Dispatcher スレッドとは異なるスレッドからその SourceCollection への変更をサポートしません。

   場所 System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)

   場所 Livet.ObservableSynchronizedCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args)

   場所 Livet.ObservableSynchronizedCollection`1.<Clear>b__12_2(Int32 count)

   場所 Livet.ObservableSynchronizedCollection`1.ReadAndWriteWithLockAction[TResult](Func`1 readBeforeWriteAction, Action`1 writeAction, Action`1 readAfterWriteAction)

   場所 Livet.ObservableSynchronizedCollection`1.Clear()

   場所 SRNicoNico.Models.NicoNicoWrapper.NicoNicoLiveNotify.<GetLiveInformationAsync>d__6.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   場所 SRNicoNico.ViewModels.LiveNotifyViewModel.<Initialize>d__7.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   場所 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   場所 System.Threading.ThreadPoolWorkQueue.Dispatch()

   場所 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
OK   
---------------------------

**Comment by mrtska** [comment]
1.19で修正しました。報告ありがとうございました。
