### ISSUE TITLE
動画コメントが取得できない

### ISSUE THREAD

**Issue by rantaro13** [mrtska/SRNicoNico#128]
すべての動画でコメントが取得できずずっと読み込み中となります。
特にエラー表示もないため何が問題なのかわかりません。

**Comment by mrtska** [comment]
私は問題なく取得できています。
一般会員の方でしょうか？

**Comment by rantaro13** [comment]
いえ、プレミアム会員です。

**Comment by makwot** [comment]
推奨のwin10では問題なし。win7では同状態ですね。
後者は再生時、windowsログにprotocol_versionのエラー。

**Comment by rantaro13** [comment]
Win7ですがprotocol_versionのエラーはなく、「次の致命的な警告を受け取りました: 70。」というのがWindowsログにありました。どちらにせよ推奨環境でない以上、ニコ動側の仕様変更があったのなら限界として諦めるしかなさそうですね

**Comment by mrtska** [comment]
もしかしたら、ニコニコのコメントサーバがhttps化したことによってTLS1.2が喋れないマシンでコメントが取得出来なくなっているのかもしれませんね。
https://blogs.technet.microsoft.com/outlooksupportjp/2018/01/05/tls/
この辺が関係あるかもですがWin7マシンを持っているわけではないので今の所検証は出来ていません。

**Comment by rantaro13** [comment]
レジストリの追加をしてみましたが変化はありませんでした。とはいえHTTPS化の影響はありそうですね。Win10マシンにいい加減乗り換える方向で考えます

**Comment by TENSTORM777** [comment]
私もWindows7で同じ症状が発生していましたが、このレジストリを導入したら、無事にコメントが表示されました。
[https://mycloudtree.co.uk/knowledgebase/19/Enabling-TLS12-on-Windows-7.html](url)

**Comment by rantaro13** [comment]
ありがとうございます、自分もそこのレジストリでコメント取得できるようになりました
