### ISSUE TITLE
動画再生中に設定からレイアウトを変更するとボタンが効かない

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#13]
動画再生中に設定の動画情報の位置を変更すると、動画が停止(音楽は流れたまま)して、
再生停止などのボタンが効かなくなります(元に戻した場合は再度効くようになります)

特に困ることではないですが、発生したので報告しておきますー

**Comment by mrtska** [comment]
報告ありがとうございます。もしかしたらこのコミット https://github.com/mrtska/SRNicoNico/commit/f2c3bb52adc0ae8669560b7f7e7ada310a51b91d
で治ってるかもしれません。
