### ISSUE TITLE
ファイル 'Icons\Category.png' が見つかりません。と表示される			

### ISSUE THREAD

**Issue by masanishi** [mrtska/SRNicoNico#14]
ビルド時にエラーが発生し
「ファイル 'Icons\Category.png' が見つかりません。	SRNicoNico 」
と表示されました。
調べるとIconsフォルダの中にCategory.pngが無かったので追加ミスではないかなと思います。

**Comment by mrtska** [comment]
すみません勘違いしてました。このCategory.pngはカテゴリタグの左につけるアイコンなのですが、仰るとおり追加するのを忘れてます。
ただ、16*16の画像なので正直ベクターグラフィックスにしようかと思っております。
書き換えるまで少々お待ちください。

**Comment by masanishi** [comment]
対応ありがとうございます！
わかりました！
そしたら今は自分で何か試す際は、何か代わりの画像を入れておけば対応できますね。
お忙しいと思いますが更新よろしくお願いします。

**Comment by mrtska** [comment]
思いの外ベクターグラフィックスで書くのが面倒になってしまったので普通に該当画像を追加しました。
ご迷惑をお掛けしました。
