### ISSUE TITLE
タグの開く先について(WebView or 別ブラウザ)

### ISSUE THREAD

**Issue by endvald** [mrtska/SRNicoNico#145]
タグの大百科ボタンを押した際に、WebViewではなく通常のChrome等で開くようなオプションがほしいです。
(WebViewだと頻繁にフリーズします)

**Comment by mrtska** [comment]
設定項目として用意するのは少々厳しかったのでShiftを押しながらクリックすることで強制的にブラウザで開くようにしてみました。

**Comment by endvald** [comment]
ありがとうございます!
