### ISSUE TITLE
特定の動画を開くとクラッシュする。

### ISSUE THREAD

**Issue by KimidoriBoushi3** [mrtska/SRNicoNico#199]
全てではないが、一部動画を開いた際にクラッシュしました。
確認できたのは次です。

https://www.nicovideo.jp/watch/sm43420029
https://www.nicovideo.jp/watch/sm43420702
https://www.nicovideo.jp/watch/sm43394768

ただ開ける動画もあるので、法則は不明です。

**Comment by mrtska** [comment]
新しい動画はダメみたいです。対応するのでしばしお待ちください～

**Comment by mrtska** [comment]
ストアの申請通りましたのでクローズしますね:pray:
