### ISSUE TITLE
通報された動画が読み込めない

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#3]
通報された動画が読み込むことができないようです

常に「?watch_harmful=1」をつければとりあえずは回避できそうです

**Comment by mrtska** [comment]
そうですね。
通報された動画に関しては公式のように警告ダイアログを作って表示したいなと今のところ思っています。

**Comment by S--Minecraft** [comment]
見つけたので張っておきますー
http://www.nicovideo.jp/watch/sm23668734

**Comment by mrtska** [comment]
ありがとうございます。 しかし私の環境では普通に再生されて出来てしまいました・・・
アカウントを変えてもダメだったので同しようもない感が漂ってきてます・・・
仕方ないのでとりあえずは?watch_harmfull=1を常に付けることにします
