### ISSUE TITLE
コミュニティ動画を読み込むとコメントが取得できない

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#5]
コミュニティに追加されている動画のコミュニティの方のurlを読み込むと、
コメントが取得できませんでしたとなって、コメントが取得できないです

コミュニティ動画から元動画へ飛ばすか、元動画からコメントだけを取得するかなどをすると
よいかなと

**Comment by mrtska** [comment]
Webでも同じような問題が発生するんですよね。
ニコニコのク○仕様と言わざるをえないのですが、やはり元動画に飛ばす処理があってもいいかもしれませんね。

**Comment by mrtska** [comment]
やはりコミュニティ動画と元動画は別扱いでいい気がします。元の動画に飛ばす処理と言っても少々難しそうですね。動画によってはコメントできない方はこちら 的なものを追加している人も居ますから現状維持ということにしようと思います。
