### ISSUE TITLE
[Bug] 再生終了時に動画移転が上手く行われない

### ISSUE THREAD

**Issue by katabamia** [mrtska/SRNicoNico#57]
動画再生終了時に自動的に動画を移転する場合、移転先の動画が読み込まれずに`動画情報`, `動画`の欄が空白となります。

その状態でシークやツイートを行おうとすると #56 と同じエラーが発生します。

**Comment by mrtska** [comment]
いまいち状況がよく分からないのですが、連続再生時の話でしょうか。
それとも連続再生時の話でしょうか。
プレミアムアカウントか一般会員アカウントかでまた話も変わってきますね。

**Comment by katabamia** [comment]
一般会員のアカウントです。
動画投稿者側で再生終了時に別の動画に移転させるスクリプトが設定されている場合に発生しました。
マイリストの連続再生で発生するかどうかはまだ確認していません。

**Comment by mrtska** [comment]
すみません。寝ぼけてたのか分からないですが文章がおかしかったので修正しました・・・

**Comment by katabamia** [comment]
一般会員で通常再生時、動画投稿者により再生終了時の動画移転スクリプトがある場合
に発生しました。

(ブラウザでの再生時に`不適切な動画の警告`が出るのでそちらも関連があるかもしれません。)

発生動画のURLは動画の内容を不快に思う方がいるかもしれないのであえて貼らずに居させてもらっています...

**Comment by mrtska** [comment]
あぁ、恐らく原因はそれでしょうね。
私はちょっと前からその警告が出なくなったのでデバッグのしようがないのはそうなんですが対策はしてみます。
