### ISSUE TITLE
動画読み込み中にボタンをクリックすると落ちる

### ISSUE THREAD

**Issue by S--Minecraft** [mrtska/SRNicoNico#6]
あまり状況が絞りこめていませんが、
通信していて、動画を読み込んでいる途中にボタンを
押して音量などを変更しようとするとクラッシュします

おそらくまだ読み込まれていない動画に対して変更しようとして
落ちるのではないかなと思います

**Comment by mrtska** [comment]
私も何度かなったことがあります。
ボタンを押せなくするなどの処置を取ろうと思っています。

**Comment by mrtska** [comment]
https://github.com/mrtska/SRNicoNico/commit/19870dc154364c99f41de78d5816eeceb435a376
修正完了しました
