### ISSUE TITLE
ツイート画面がツイートをするまで閉じることが出来ない

### ISSUE THREAD

**Issue by katabamia** [mrtska/SRNicoNico#60]
動画再生時のツイートボタンが何かしらのツイートをするまで閉じることが出来ません。
(メインウィンドウをクリックでアクティブにしてもツイートウィンドウが表示されたままになる)

ツイートウィンドウのアクティブが外れた場合にツイートウィンドウを閉じる
もしくはツイートウィンドウに閉じるボタンの実装をお願いいたいます。

**Comment by mrtska** [comment]
一応 Escで閉じられます。
ただ、どこにも書いてなかったですね。
今度HelpViewあたりに書いておきます。

**Comment by katabamia** [comment]
ありがとうございます🙇🏼
