### ISSUE TITLE
リピート再生時にプログレスバーの背景色が初期化されない

### ISSUE THREAD

**Issue by katabamia** [mrtska/SRNicoNico#61]
1回目再生時には
再生済: テーマ色
読込済: 明るい灰色
未読込: 暗い灰色
となっていますが、リピート再生時の2回目以降には背景色が初期化されずに1回目再生時の状態のままとなっています。

1回目再生時
![](http://i.imgur.com/WMS7Bbt.png)

2回目以降
![](http://i.imgur.com/ukVChcn.png)

**Comment by mrtska** [comment]
申し訳ありませんが、仕様です。
意図した動作です。

**Comment by katabamia** [comment]
了解しました 👌
