### ISSUE TITLE
マイリストを開いたらエラー

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#62]
---------------------------
エラー
---------------------------
不明なエラーが発生しました。可能であれば、この文章をコピーして作者に報告していただれば幸いです。Ctrl+Cでコピーできます。
 ExceptionObject:System.ArgumentOutOfRangeException: StartIndex の値を 0 より小さくすることはできません。

パラメーター名:startIndex

   場所 System.String.Substring(Int32 startIndex, Int32 length)

   場所 SRNicoNico.Models.NicoNicoWrapper.NicoNicoPublicMylist.<GetMylistAsync>d__3.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   場所 SRNicoNico.ViewModels.PublicMylistViewModel.<Initialize>d__17.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()

   場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   場所 System.Windows.Threading.DispatcherOperation.Invoke()

   場所 System.Windows.Threading.Dispatcher.ProcessQueue()

   場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   場所 System.Windows.Application.RunDispatcher(Object ignore)

   場所 System.Windows.Application.RunInternal(Window window)

   場所 System.Windows.Application.Run(Window window)

   場所 SRNicoNico.App.Main()
---------------------------
OK   
---------------------------
マイリストを1つ開いた状態で更にもう1つ開こうとしたら、このエラーを出してクラッシュしました。

**Comment by mrtska** [comment]
このエラー、確定で出ます？
あとプレミアム会員です？

**Comment by cyatarow** [comment]
プレミアムではありません。
適当にマイリストを開いていたらいきなりこうなりました。

**Comment by mrtska** [comment]
該当のマイリストが分かればおそらく直ぐに解決出来そうなのですが分かりますか？

**Comment by cyatarow** [comment]
http://www.nicovideo.jp/mylist/13599045
sm17418112の動画説明欄に書かれていたのですが、ブラウザで見ると非公開マイリストのようでした。
