### ISSUE TITLE
コミュを開くとエラー

### ISSUE THREAD

**Issue by ZenZincum** [mrtska/SRNicoNico#64]
フォローしているコミュニティや放送中のコミュニティ欄からコミュニティに飛ぶと大体がエラーをはいて動作停止になります。
参考までに、エラーになったコミュは
co1124417
co1788380　など
エラーを出さなかったコミュは
co231630　などです。
エラー原因にコミュプロフィールの行数や文字数は関係ないようです。

一般会員、Win10Proです。

<pre><code> ExceptionObject:System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。

   場所 SRNicoNico.Models.NicoNicoWrapper.NicoNicoCommunity.<GetCommunityAsync>d__3.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   場所 SRNicoNico.ViewModels.CommunityViewModel.<Initialize>d__10.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()

   場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   場所 System.Windows.Threading.DispatcherOperation.Invoke()

   場所 System.Windows.Threading.Dispatcher.ProcessQueue()

   場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   場所 System.Windows.Application.RunDispatcher(Object ignore)

   場所 System.Windows.Application.RunInternal(Window window)

   場所 System.Windows.Application.Run(Window window)

   場所 SRNicoNico.App.Main()</code></pre>

**Comment by mrtska** [comment]
報告ありがとうございます。

コミットメッセージのとおりです。

いつも丁寧にありがとうございます。
次回アップデートで修正されます。
