### ISSUE TITLE
動画読み込み中のアニメーション（点の回転）が動画画面以外でも表示される

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#76]
タイトルの通りです。
バッファが足りないなどの理由で動画を読み込んでいるとき、動画読み込みのアニメーションが出てきますが、そのアニメーションが他の画面を表示していても出てきます。
NicoNicoViewerのウィンドウに、他のウィンドウを重ねて表示していてもアニメーションが出てきます。

**Comment by mrtska** [comment]
そうなんですよね。
WebViewなどのWPFでない要素の上にはWPFのプログレスリングが表示できないので透明なポップアップの上に描画しているのですが、特に対策等はしていないのでご指摘のような事象が起きますね。

どうするかちょっと考えます。

**Comment by mrtska** [comment]
覚えてないですが、どこかのタイミングで直してました。
