### ISSUE TITLE
動画を画面クリックで一時停止するとエラー発生

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#80]
sm10389260で、0:58のところで、画面をクリックして一時停止したところ、エラーが発生しました。一般会員です。

---------------------------
エラー
---------------------------
不明なエラーが発生しました。可能であれば、この文章をコピーして作者に報告していただれば幸いです。Ctrl+Cでコピーできます。
動画再生時に起きた場合は動画IDを添えてください。
 ExceptionObject:System.Xml.XmlException: 予期しない文字 '<' が見つかりました。

   場所 System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)

   場所 System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()

   場所 System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)

   場所 System.Runtime.Serialization.Json.XmlJsonReader.Read()

   場所 System.Xml.XmlBaseReader.MoveToContent()

   場所 System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)

   場所 Codeplex.Data.DynamicJson.Parse(String json, Encoding encoding)

   場所 SRNicoNico.Models.NicoNicoWrapper.NicoNicoWatchApi.<RecordPlaybackPositionAsync>d__7.MoveNext()

--- 直前に例外がスローされた場所からのスタック トレースの終わり ---

   場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()

   場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   場所 System.Windows.Threading.DispatcherOperation.Invoke()

   場所 System.Windows.Threading.Dispatcher.ProcessQueue()

   場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   場所 System.Windows.Application.RunDispatcher(Object ignore)

   場所 System.Windows.Application.RunInternal(Window window)

   場所 System.Windows.Application.Run(Window window)

   場所 SRNicoNico.App.Main()
---------------------------
OK   
---------------------------

**Comment by mrtska** [comment]
同じ条件で試しましたが特に何も起きませんでした。
スタックトレースと状況を見る限り、現在再生位置を保存する時にNicoNicoから変なレスポンスがあってクラッシュしたと見られます。再現はしなかったのでとりあえずは様子見ということで・・・
