### ISSUE TITLE
ずっと起動していると、タスクバーにNicoNicoViewerが出てこなくなる

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#90]
何でもいいのでたくさん動画を見ると、タスクバーにNicoNicoViewerが出てこなくなります。
その状態でウィンドウを最小化すると、Alt+Tabまたはタスクマネージャを使わないとウィンドウを再表示できません。

**Comment by mrtska** [comment]
私も極稀にこの現象が起きるのですが原因がNicoNicoViewerなのかWPFなのか使っているライブラリなのか検討もつきません。
エクスプローラを再起動したら出てきたりするのでしょうかね・・・

**Comment by mrtska** [comment]
最近はタスクバーからいなくなることもないですが、今も続きますでしょうか。
私も見なくなったのでまた再現したら再度お知らせいただけますか。
