### ISSUE TITLE
バージョン1.14に更新するのに.NET Framework 4.7が必要であるとのメッセージ

### ISSUE THREAD

**Issue by cyatarow** [mrtska/SRNicoNico#97]
---------------------------
SRNicoNico.exe - This application could not be started.
---------------------------
This application requires one of the following versions of the .NET Framework:
 .NETFramework,Version=v4.7

Do you want to install this .NET Framework version now?
---------------------------
はい(Y)   いいえ(N)   
---------------------------

作者様はTwitterで「普通にWindows 10を使っていれば何もしなくても起動はずです」とおっしゃっていましたが、Windows 10でも、**バージョン1511だと.NET Framework 4.7のインストール時に弾かれる**ようです。
調べると、.NET Framework 4.7をインストールできるWindows 10はAnniversary Update以降だけとのことです。
https://github.com/dotnet/docs.ja-jp/blob/master/docs/framework/get-started/system-requirements.md

僕はWindowsをむやみに更新したくはありません。しかし、.NET Framework 4.7がインストールできないので、このままではNicoNicoViewerを利用できません。どうしたらいいでしょう？

**Comment by mrtska** [comment]
http://internet.watch.impress.co.jp/docs/news/1073028.html
こちらをお読みください。
私が言う普通にWindows10を使うというのは大型Windows Updateを当てていることを指しています。
申し訳ありませんが、あと1ヶ月もしないでサポートが切れるバージョンのサポートをする予定はありません。
